import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useAuth } from '../auth/AuthProvider.jsx';
import { EmptyState, ErrorState, Loading, MetricCard, StatusPill } from '../components/ui.jsx';

export const AdminWorkspace = () => {
  const { api } = useAuth(); const client = useQueryClient();
  const overview = useQuery({ queryKey: ['relay-admin'], queryFn: () => api.get('/api/admin/overview') });
  const updateUser = useMutation({ mutationFn: ({ uid, disabled }) => api.patch(`/api/admin/users/${uid}`, { disabled }), onSuccess: () => client.invalidateQueries({ queryKey: ['relay-admin'] }) });
  if (overview.isLoading) return <Loading label="Loading Relay owner console…" />;
  if (overview.error) return <ErrorState error={overview.error} />;
  const { metrics, projects, users } = overview.data.data;
  return <section className="space-y-7"><div><p className="label text-relay-400">Relay owner</p><h1 className="mt-2 text-3xl font-semibold">Administration</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">Fleet-wide visibility and account control. Actions here affect the Relay service, not just one project.</p></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Accounts" value={metrics.users} detail={`${metrics.disabledUsers} suspended`} /><MetricCard label="Projects" value={metrics.projects} detail={`${metrics.backends} backends`} /><MetricCard label="Unhealthy" value={metrics.unhealthy} detail="Across all projects" tone={metrics.unhealthy ? 'red' : 'green'} /><MetricCard label="Active failovers" value={metrics.activeFailovers} detail="Require attention" tone={metrics.activeFailovers ? 'red' : 'blue'} /></div><article className="panel overflow-hidden"><div className="border-b border-white/10 p-5"><h2 className="font-semibold">Projects and service health</h2><p className="mt-1 text-sm text-slate-400">Every customer project, its backend count, routing mode, and current status.</p></div>{projects.length ? <div className="divide-y divide-white/10">{projects.map((project) => <div className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center sm:justify-between" key={project.id}><div><p className="font-medium">{project.name}</p><p className="mt-1 text-xs text-slate-500">{project.id} · {project.backends} backends · Owner {project.ownerId}</p></div><div className="flex items-center gap-3"><span className="text-xs text-slate-400">{project.statuses.HEALTHY ?? 0} healthy / {project.statuses.UNHEALTHY ?? 0} down</span><StatusPill status={project.failoverMode} /></div></div>)}</div> : <EmptyState title="No projects yet" />}</article><article className="panel overflow-hidden"><div className="border-b border-white/10 p-5"><h2 className="font-semibold">Accounts</h2><p className="mt-1 text-sm text-slate-400">Suspend a compromised or inactive account; restore access when it is safe.</p></div><div className="divide-y divide-white/10">{users.map((user) => <div className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center sm:justify-between" key={user.uid}><div><p className="font-medium">{user.displayName || 'Unnamed user'}</p><p className="mt-1 text-sm text-slate-400">{user.email || user.uid}</p><p className="mt-1 text-xs text-slate-500">{user.emailVerified ? 'Email verified' : 'Unverified'} · {user.disabled ? 'Suspended' : 'Active'}</p></div><button className="btn-secondary" disabled={updateUser.isPending} onClick={() => updateUser.mutate({ uid: user.uid, disabled: !user.disabled })}>{user.disabled ? 'Restore access' : 'Suspend account'}</button></div>)}</div></article></section>;
};
