import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { GoogleAuthProvider, createUserWithEmailAndPassword, sendEmailVerification, signInWithEmailAndPassword, signInWithPopup, signInWithRedirect, updateProfile } from 'firebase/auth';
import { authActionSettings, firebaseAuth } from '../firebase.js';
import { useAuth } from '../auth/AuthProvider.jsx';
import { authMessage } from '../auth/messages.js';

const PASSWORD_MIN_LENGTH = 12;
const PASSWORD_MAX_LENGTH = 128;

const GoogleMark = () => <svg aria-hidden="true" className="h-5 w-5" viewBox="0 0 24 24"><path fill="#4285F4" d="M21.35 12.23c0-.71-.06-1.39-.18-2.05H12v3.88h5.24a4.48 4.48 0 0 1-1.94 2.94v2.52h3.24c1.9-1.75 2.99-4.33 2.99-7.29Z" /><path fill="#34A853" d="M12 21.8c2.64 0 4.85-.88 6.47-2.38L15.23 17a5.82 5.82 0 0 1-8.67-3.06H3.22v2.6A9.77 9.77 0 0 0 12 21.8Z" /><path fill="#FBBC05" d="M6.56 13.94a5.85 5.85 0 0 1 0-3.74V7.6H3.22a9.8 9.8 0 0 0 0 8.94l3.34-2.6Z" /><path fill="#EA4335" d="M12 6.35c1.52 0 2.88.52 3.96 1.54l2.97-2.97C16.84 2.97 14.63 1.8 12 1.8a9.77 9.77 0 0 0-8.78 5.8l3.34 2.6A5.82 5.82 0 0 1 12 6.35Z" /></svg>;

export const AuthPage = ({ register = false }) => {
  const navigate = useNavigate(); const { firebaseConfigured, authIssue, clearAuthIssue } = useAuth();
  const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [working, setWorking] = useState(false);
  const submit = async (event) => {
    event.preventDefault();
    if (register && (!name.trim() || password.length < PASSWORD_MIN_LENGTH || password.length > PASSWORD_MAX_LENGTH)) { setError(`Enter your name and use a password between ${PASSWORD_MIN_LENGTH} and ${PASSWORD_MAX_LENGTH} characters.`); return; }
    setWorking(true); setError(''); clearAuthIssue();
    try {
      if (register) { const credential = await createUserWithEmailAndPassword(firebaseAuth, email, password); await updateProfile(credential.user, { displayName: name.trim() }); await sendEmailVerification(credential.user, authActionSettings); }
      else await signInWithEmailAndPassword(firebaseAuth, email, password);
      navigate('/dashboard');
    } catch (reason) { setError(authMessage(reason, register ? 'We could not create your account. Please review your details and try again.' : 'We could not sign you in. Check your email and password, then try again.')); } finally { setWorking(false); }
  };
  const signInWithGoogle = async () => { setWorking(true); setError(''); clearAuthIssue(); try { const provider = new GoogleAuthProvider(); try { await signInWithPopup(firebaseAuth, provider); } catch (reason) { if (reason.code !== 'auth/popup-blocked') throw reason; await signInWithRedirect(firebaseAuth, provider); return; } navigate('/dashboard'); } catch (reason) { setError(authMessage(reason, 'Google sign-in could not be completed. Please try again.')); } finally { setWorking(false); } };
  return <div className="grid min-h-screen place-items-center bg-[radial-gradient(ellipse_at_top,_rgba(28,125,242,0.24),_transparent_45%),#06172d] px-5"><section className="w-full max-w-md panel p-7 sm:p-9"><div className="flex items-center gap-2 text-xl font-semibold"><img className="h-9 w-9 object-contain" src="/relay-mark.png" alt="" />Relay</div><h1 className="mt-8 text-2xl font-semibold tracking-tight">{register ? 'Create your Relay workspace' : 'Welcome back'}</h1><p className="mt-2 text-sm leading-6 text-slate-400">{register ? 'Use a work email to create a secure reliability workspace.' : 'Sign in to manage your Relay projects and gateway policies.'}</p>{!firebaseConfigured ? <div className="mt-6 rounded-xl border border-amber-300/30 bg-amber-300/10 p-4 text-sm text-amber-100">Sign-in is not configured for this environment. Please contact the workspace owner.</div> : <><form className="mt-7 space-y-5" onSubmit={submit}>{register && <label className="block"><span className="label">Full name</span><input className="field" autoComplete="name" maxLength="80" value={name} onChange={(event) => setName(event.target.value)} required /></label>}<label className="block"><span className="label">Email address</span><input className="field" autoComplete="email" type="email" maxLength="254" value={email} onChange={(event) => setEmail(event.target.value)} required /></label><label className="block"><span className="label">Password</span><input className="field" autoComplete={register ? 'new-password' : 'current-password'} type="password" minLength={register ? PASSWORD_MIN_LENGTH : 1} maxLength={PASSWORD_MAX_LENGTH} value={password} onChange={(event) => setPassword(event.target.value)} required />{register && <span className="mt-2 block text-xs text-slate-500">Use {PASSWORD_MIN_LENGTH}–{PASSWORD_MAX_LENGTH} characters. Your account password policy may require more.</span>}</label>{!register && <div className="text-right"><Link className="text-sm font-medium text-relay-400 hover:text-relay-300" to="/forgot-password">Forgot password?</Link></div>}{(error || authIssue) && <p className="text-sm text-rose-200" role="alert">{error || authIssue}</p>}<button className="btn-primary w-full" disabled={working}>{working ? 'Please wait…' : register ? 'Create account' : 'Sign in'}</button></form><div className="my-6 flex items-center gap-3 text-xs text-slate-500"><span className="h-px flex-1 bg-white/10" />or<span className="h-px flex-1 bg-white/10" /></div><button className="btn-secondary w-full gap-3" onClick={signInWithGoogle} disabled={working}><GoogleMark />Continue with Google</button></>}<p className="mt-6 text-center text-sm text-slate-400">{register ? 'Already have an account?' : 'New to Relay?'} <Link className="font-semibold text-relay-400 hover:text-relay-300" to={register ? '/login' : '/register'}>{register ? 'Sign in' : 'Create an account'}</Link></p></section></div>;
};
