import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useAuth } from '../auth/AuthProvider.jsx';
import { EmptyState, ErrorState, Loading } from '../components/ui.jsx';

const scopes = ['project:read', 'project:write', 'monitoring:read', 'monitoring:write', 'gateway:read', 'gateway:write', 'usage:read'];

export const ApiKeys = () => {
  const { api } = useAuth(); const client = useQueryClient();
  const [name, setName] = useState(''); const [selectedScopes, setSelectedScopes] = useState(['project:read']); const [secret, setSecret] = useState('');
  const keys = useQuery({ queryKey: ['api-keys'], queryFn: () => api.get('/api/api-keys') });
  const create = useMutation({ mutationFn: () => api.post('/api/api-keys', { name, scopes: selectedScopes }), onSuccess: (result) => { setSecret(result.data.key); setName(''); client.invalidateQueries({ queryKey: ['api-keys'] }); } });
  const revoke = useMutation({ mutationFn: (id) => api.delete(`/api/api-keys/${id}`), onSuccess: () => client.invalidateQueries({ queryKey: ['api-keys'] }) });
  const toggleScope = (scope) => setSelectedScopes((current) => current.includes(scope) ? current.filter((item) => item !== scope) : [...current, scope]);
  if (keys.isLoading) return <Loading />; if (keys.error) return <ErrorState error={keys.error} />;
  return <section className="space-y-6"><div><p className="label text-relay-400">Developer access</p><h1 className="mt-2 text-3xl font-semibold">API keys</h1><p className="mt-2 text-sm text-slate-400">Keys are scoped, hashed at rest, and shown only once. Store a new key in your secret manager immediately.</p></div>{secret && <div className="rounded-xl border border-amber-300/30 bg-amber-300/10 p-5"><p className="font-semibold text-amber-100">Copy this API key now</p><code className="mt-3 block overflow-auto rounded-lg bg-black/25 p-3 text-sm text-amber-100">{secret}</code><p className="mt-2 text-sm text-amber-100/80">It will not be shown again.</p><button className="btn-secondary mt-4" onClick={() => setSecret('')}>I stored it safely</button></div>}<form className="panel space-y-4 p-5" onSubmit={(event) => { event.preventDefault(); create.mutate(); }}><h2 className="font-semibold">Create API key</h2><label className="block"><span className="label">Key name</span><input className="field" value={name} onChange={(event) => setName(event.target.value)} placeholder="CI deployment reader" minLength="2" maxLength="80" required /></label><fieldset><legend className="label">Scopes</legend><div className="mt-2 grid gap-2 sm:grid-cols-2">{scopes.map((scope) => <label className="flex items-center gap-2 rounded-lg border border-white/10 p-2 text-sm" key={scope}><input type="checkbox" checked={selectedScopes.includes(scope)} onChange={() => toggleScope(scope)} />{scope}</label>)}</div></fieldset>{create.error && <p className="text-sm text-rose-200">{create.error.message}</p>}<button className="btn-primary" disabled={create.isPending || !selectedScopes.length}>{create.isPending ? 'Creating…' : 'Create key'}</button></form>{keys.data.data.length ? <div className="panel divide-y divide-white/10">{keys.data.data.map((key) => <article className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center sm:justify-between" key={key.id}><div><p className="font-medium">{key.name}</p><p className="mt-1 font-mono text-xs text-slate-400">{key.prefix}…</p><p className="mt-2 text-xs text-slate-500">{key.scopes.join(', ')} · {key.revokedAt ? 'Revoked' : 'Active'}</p></div>{!key.revokedAt && <button className="btn-secondary" onClick={() => revoke.mutate(key.id)} disabled={revoke.isPending}>Revoke</button>}</article>)}</div> : <EmptyState title="No API keys yet">Use Firebase Authentication for dashboard access, or create a scoped key for machine-to-machine calls.</EmptyState>}</section>;
};

export const Settings = () => <section className="space-y-4"><p className="label text-relay-400">Workspace</p><h1 className="text-3xl font-semibold">Settings</h1><EmptyState title="Workspace settings">Firebase Authentication is the identity provider. Team roles are modeled for OWNER, ADMIN, DEVELOPER, and VIEWER; the initial control plane enforces owner changes.</EmptyState></section>;
