import { Link } from 'react-router-dom';

const icons = {
  route: <><path d="M4 7h11a3 3 0 1 1 0 6H9" /><path d="m12 4 3 3-3 3M12 10l-3 3 3 3" /></>,
  shield: <><path d="M12 3 5.5 6v5.5c0 4.2 2.7 7.2 6.5 8.5 3.8-1.3 6.5-4.3 6.5-8.5V6L12 3Z" /><path d="m9.5 11.5 1.7 1.7 3.5-3.7" /></>,
  switch: <><path d="M5 7h11" /><path d="m13 4 3 3-3 3M19 17H8" /><path d="m11 14-3 3 3 3" /></>,
  pulse: <><path d="M3 12h3l2-5 4 10 2-5h7" /></>,
  clock: <><circle cx="12" cy="12" r="8.5" /><path d="M12 7v5l3.5 2" /></>,
  limit: <><path d="M5 17 17 5" /><path d="M6.5 6.5h.01M17.5 17.5h.01" /><circle cx="12" cy="12" r="8.5" /></>,
  stack: <><rect x="4" y="5" width="16" height="4" rx="1" /><rect x="4" y="11" width="16" height="4" rx="1" /><path d="M7 17h10" /></>,
  chart: <><path d="M4 19V5M4 19h16" /><path d="m7 15 3-3 3 2 5-6" /></>
};

const Icon = ({ name }) => <span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl border border-relay-300/25 bg-relay-300/10 text-relay-200"><svg aria-hidden="true" className="h-5 w-5" fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.8" viewBox="0 0 24 24">{icons[name]}</svg></span>;

const services = [
  ['route', 'Smart traffic routing', 'Send application traffic through one Relay gateway and direct it to the right registered backend.'],
  ['shield', 'Backend protection', 'Use a stable gateway address so frontend applications do not need to depend on each backend origin.'],
  ['switch', 'Automatic failover', 'Connect primary and standby backends, then switch only after health evidence confirms an outage.'],
  ['pulse', 'Health monitoring', 'Track availability, response results, failures, and service health from one workspace.'],
  ['clock', 'Keep-alive management', 'Run scheduled health probes to help public backends remain responsive and observable.'],
  ['limit', 'Rate limiting', 'Control excessive gateway traffic and help protect backend resources from unwanted usage.'],
  ['stack', 'Multi-backend management', 'Organize backends, environments, and projects from a single Relay account.'],
  ['chart', 'Unified monitoring', 'See status, incidents, latency signals, and failover events together.']
];

const Metric = ({ label, value, tone = 'text-white' }) => <div className="rounded-xl border border-white/10 bg-white/[0.035] p-4"><p className="text-[11px] font-semibold uppercase tracking-[0.12em] text-slate-500">{label}</p><p className={`mt-2 text-2xl font-semibold tracking-tight ${tone}`}>{value}</p></div>;

const Status = ({ label, value, tone }) => <div className="flex items-center justify-between gap-4 py-3 text-sm"><span className="font-medium text-slate-200">{label}</span><span className={`inline-flex items-center gap-1.5 text-xs font-semibold ${tone}`}><i className="h-1.5 w-1.5 rounded-full bg-current" />{value}</span></div>;

export const LandingPage = () => <main className="min-h-screen overflow-hidden bg-[#06172d] text-white">
  <div className="pointer-events-none absolute inset-x-0 top-0 h-[41rem] bg-[radial-gradient(circle_at_56%_-8%,rgba(37,133,255,0.38),transparent_52%)]" />
  <header className="relative mx-auto flex max-w-6xl items-center justify-between px-5 py-5 sm:px-8">
    <Link className="flex items-center gap-2 text-xl font-semibold tracking-tight" to="/"><img className="h-9 w-9 object-contain" src="/relay-mark.png" alt="Relay" />Relay</Link>
    <nav className="hidden items-center gap-7 text-sm text-slate-300 md:flex"><a href="#services" className="transition hover:text-white">Services</a><a href="#architecture" className="transition hover:text-white">Architecture</a><a href="#monitoring" className="transition hover:text-white">Monitoring</a></nav>
    <div className="flex items-center gap-3"><Link className="text-sm font-medium text-slate-300 transition hover:text-white" to="/login">Sign in</Link><Link className="rounded-lg bg-relay-400 px-4 py-2 text-sm font-semibold text-white shadow-lg shadow-relay-500/20 transition hover:bg-relay-300" to="/register">Get started</Link></div>
  </header>

  <section className="relative mx-auto grid max-w-6xl gap-12 px-5 pb-20 pt-14 sm:px-8 lg:grid-cols-[0.9fr_1.1fr] lg:items-center lg:pt-24">
    <div><p className="inline-flex rounded-full border border-relay-300/30 bg-relay-300/10 px-3 py-1 text-xs font-semibold text-relay-100">Reliability, controlled</p><h1 className="mt-6 max-w-xl text-4xl font-semibold leading-[1.08] tracking-tight sm:text-6xl">A reliable control layer for your backends.</h1><p className="mt-6 max-w-lg text-base leading-7 text-slate-300">Manage, protect, monitor, and route your application backends from one centralized platform.</p><div className="mt-8 flex flex-wrap gap-3"><Link className="rounded-lg bg-relay-400 px-5 py-3 text-sm font-semibold text-white shadow-xl shadow-relay-500/20 transition hover:bg-relay-300" to="/register">Get started</Link><a className="rounded-lg border border-white/15 px-5 py-3 text-sm font-semibold text-slate-200 transition hover:bg-white/5" href="#monitoring">Explore Relay</a></div><p className="mt-8 text-sm text-slate-500">Routing · Protection · Monitoring · Failover · Management</p></div>
    <DashboardPreview />
  </section>

  <section id="services" className="relative border-y border-white/10 bg-[#081a31]/70 py-20"><div className="mx-auto max-w-6xl px-5 sm:px-8"><div className="max-w-2xl"><p className="label text-relay-300">Core services</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Everything your backend layer needs, in one place.</h2></div><div className="mt-10 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{services.map(([icon, title, copy]) => <article className="rounded-2xl border border-white/10 bg-white/[0.035] p-5 transition hover:-translate-y-0.5 hover:border-relay-300/35" key={title}><Icon name={icon} /><h3 className="mt-5 font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{copy}</p></article>)}</div></div></section>

  <section id="architecture" className="relative mx-auto max-w-6xl px-5 py-20 sm:px-8"><div className="grid gap-12 lg:grid-cols-[0.72fr_1.28fr] lg:items-center"><div><p className="label text-relay-300">Relay architecture</p><h2 className="mt-3 text-3xl font-semibold tracking-tight">One gateway. Multiple resilient paths.</h2><p className="mt-4 max-w-sm text-sm leading-7 text-slate-400">Frontend applications communicate with one stable Relay endpoint. Relay applies traffic controls and routes each request to the active registered backend.</p><div className="mt-7 space-y-3 text-sm text-slate-300"><p><span className="font-semibold text-white">One endpoint.</span> Keep frontend configuration simple.</p><p><span className="font-semibold text-white">High availability.</span> Use backup destinations when the primary fails.</p><p><span className="font-semibold text-white">Provider independent.</span> Connect cloud, VPS, and self-hosted backends.</p></div></div><Architecture /></div></section>

  <section id="monitoring" className="relative border-y border-white/10 bg-[#081a31]/70 py-20"><div className="mx-auto max-w-6xl px-5 sm:px-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="label text-relay-300">Unified monitoring</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">A calm view of backend health.</h2></div><p className="max-w-sm text-sm leading-6 text-slate-400">A focused workspace for projects, backend status, incidents, response signals, and failover activity.</p></div><MonitoringPreview /></div></section>

  <section className="relative mx-auto max-w-6xl px-5 py-20 sm:px-8"><div className="rounded-3xl border border-relay-300/20 bg-[linear-gradient(110deg,rgba(30,120,242,0.18),rgba(109,70,220,0.12))] p-8 sm:p-12"><div className="grid gap-8 lg:grid-cols-[1.1fr_0.9fr] lg:items-center"><div><p className="label text-relay-200">Built for dependable applications</p><h2 className="mt-3 text-3xl font-semibold tracking-tight">Your application should not depend on one backend.</h2><p className="mt-4 max-w-xl text-sm leading-7 text-slate-300">Relay gives your team a centralized layer for routing, backend protection, monitoring, and health-based failover.</p></div><div className="flex flex-wrap gap-3 lg:justify-end"><Link className="rounded-lg bg-relay-400 px-5 py-3 text-sm font-semibold text-white transition hover:bg-relay-300" to="/register">Get started</Link><a className="rounded-lg border border-white/15 px-5 py-3 text-sm font-semibold text-slate-100 transition hover:bg-white/5" href="#services">Explore Relay</a></div></div></div></section>
  <footer className="relative border-t border-white/10 px-5 py-8 text-center text-sm text-slate-500">Relay — reliability, controlled.</footer>
</main>;

const DashboardPreview = () => <div className="relative mx-auto w-full max-w-2xl"><div className="absolute -inset-7 rounded-[2rem] bg-relay-400/15 blur-3xl" /><div className="relative overflow-hidden rounded-2xl border border-white/15 bg-[#0a1c35]/95 p-4 shadow-2xl shadow-black/35"><div className="flex items-center justify-between border-b border-white/10 pb-4"><div className="flex items-center gap-2"><span className="h-2.5 w-2.5 rounded-full bg-rose-300" /><span className="h-2.5 w-2.5 rounded-full bg-amber-200" /><span className="h-2.5 w-2.5 rounded-full bg-emerald-300" /></div><span className="rounded-full bg-emerald-400/15 px-3 py-1 text-xs font-semibold text-emerald-200">Operations overview</span></div><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4"><Metric label="Projects" value="12" /><Metric label="Healthy" value="18" tone="text-emerald-200" /><Metric label="Requests" value="2,481" /><Metric label="Failovers" value="07" tone="text-relay-200" /></div><div className="mt-3 grid gap-3 sm:grid-cols-[1.2fr_0.8fr]"><div className="rounded-xl border border-white/10 bg-[#0d2340] p-4"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-slate-500">Traffic activity</p><p className="mt-2 text-lg font-semibold">Gateway requests</p></div><p className="text-sm font-semibold text-emerald-200">99.98%</p></div><div className="mt-6 flex h-20 items-end gap-1.5">{[31, 47, 43, 67, 55, 78, 62, 90, 76, 96, 83, 100].map((height, index) => <span className="flex-1 rounded-t bg-gradient-to-t from-relay-500/40 to-relay-300" style={{ height: `${height}%`, opacity: 0.42 + index / 20 }} key={`${height}-${index}`} />)}</div></div><div className="rounded-xl border border-white/10 bg-white/[0.035] px-4"><p className="pt-4 text-xs font-semibold uppercase tracking-[0.14em] text-slate-500">Backend status</p><div className="divide-y divide-white/10"><Status label="API Primary" value="Healthy" tone="text-emerald-200" /><Status label="API Backup" value="Healthy" tone="text-emerald-200" /><Status label="Auth service" value="Degraded" tone="text-amber-200" /></div></div></div><p className="mt-3 text-right text-[11px] text-slate-600">Illustrative workspace preview</p></div></div>;

const Architecture = () => <div className="rounded-3xl border border-white/10 bg-white/[0.035] p-5 sm:p-8"><div className="mx-auto flex max-w-md flex-col items-center text-center"><span className="label">Application users</span><span className="my-3 h-7 w-px bg-relay-300/50" /><div className="w-full rounded-2xl border border-relay-300/35 bg-relay-300/10 p-5 shadow-lg shadow-relay-500/10"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-relay-200">Relay gateway</p><p className="mt-2 text-sm text-slate-300">Traffic control and routing</p></div><span className="my-3 h-7 w-px bg-relay-300/50" /><div className="grid w-full grid-cols-3 gap-3">{[['Backend A', 'Primary'], ['Backend B', 'Backup'], ['Backend C', 'Fallback']].map(([name, role]) => <div className="rounded-xl border border-white/10 bg-[#0b203b] p-3" key={name}><p className="text-sm font-semibold">{name}</p><p className="mt-1 text-xs text-slate-500">{role}</p></div>)}</div><span className="my-3 h-7 w-px bg-relay-300/50" /><span className="text-sm font-medium text-slate-300">Your application</span></div></div>;

const MonitoringPreview = () => <div className="mt-10 grid gap-4 lg:grid-cols-[0.72fr_1.28fr]"><div className="grid grid-cols-2 gap-4"><Metric label="Projects" value="12" /><Metric label="Active requests" value="2,481" /><Metric label="Failed requests" value="08" tone="text-rose-200" /><Metric label="Average response" value="142 ms" tone="text-relay-200" /></div><div className="rounded-2xl border border-white/10 bg-white/[0.035] px-5"><div className="flex items-center justify-between border-b border-white/10 py-4"><div><p className="font-semibold">Backend status</p><p className="mt-1 text-xs text-slate-500">Latest observed health</p></div><span className="text-xs font-medium text-slate-400">All projects</span></div><div className="divide-y divide-white/10"><Status label="API Primary" value="Healthy" tone="text-emerald-200" /><Status label="API Backup" value="Healthy" tone="text-emerald-200" /><Status label="Auth service" value="Degraded" tone="text-amber-200" /><Status label="Payment service" value="Offline" tone="text-rose-200" /></div></div></div>;
