import { useEffect, useState } from 'react';
import { Link, NavLink, useLocation, useNavigate, useParams } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useAuth } from '../auth/AuthProvider.jsx';
import { GATEWAY_BASE_URL } from '../api/client.js';
import { EmptyState, ErrorState, Loading, StatusPill } from '../components/ui.jsx';
import { useBackendHealthTest } from '../healthTests.js';

const sections = [{ key: '', label: 'Overview' }, { key: 'backends', label: 'Backends' }, { key: 'monitoring', label: 'Monitoring' }, { key: 'gateway', label: 'Gateway' }, { key: 'failover', label: 'Failover' }, { key: 'alerts', label: 'Alerts' }, { key: 'logs', label: 'Logs' }, { key: 'settings', label: 'Settings' }];
const minutes = (seconds) => Number(seconds / 60).toLocaleString(undefined, { maximumFractionDigits: 1 });

const useProjectData = (projectId) => {
  const { api } = useAuth();
  return { project: useQuery({ queryKey: ['project', projectId], queryFn: () => api.get(`/api/projects/${projectId}`) }), backends: useQuery({ queryKey: ['backends', projectId], queryFn: () => api.get(`/api/projects/${projectId}/backends`) }) };
};

const BackendForm = ({ projectId }) => {
  const { api } = useAuth(); const client = useQueryClient(); const [form, setForm] = useState({ name: '', originUrl: '', healthPath: '/health', role: 'PRIMARY' });
  const add = useMutation({ mutationFn: () => api.post(`/api/projects/${projectId}/backends`, form), onSuccess: () => { client.invalidateQueries({ queryKey: ['backends', projectId] }); client.invalidateQueries({ queryKey: ['dashboard'] }); setForm({ name: '', originUrl: '', healthPath: '/health', role: 'PRIMARY' }); } });
  const change = (event) => setForm({ ...form, [event.target.name]: event.target.value });
  return <form className="grid gap-3 rounded-xl border border-white/10 bg-slate-950/20 p-4 md:grid-cols-2" onSubmit={(event) => { event.preventDefault(); add.mutate(); }}><label><span className="label">Backend name</span><input className="field" name="name" value={form.name} onChange={change} placeholder="Production API" minLength="2" required /></label><label><span className="label">Public origin URL</span><input className="field" name="originUrl" type="url" value={form.originUrl} onChange={change} placeholder="https://api.example.com" required /></label><label><span className="label">Health path</span><input className="field" name="healthPath" value={form.healthPath} onChange={change} required /></label><label><span className="label">Role</span><select className="field" name="role" value={form.role} onChange={change}><option value="PRIMARY">Primary</option><option value="SECONDARY">Secondary</option></select></label><p className="text-xs leading-5 text-slate-500 md:col-span-2">Relay validates origins against DNS and public-IP policy. Private, loopback, link-local, and metadata addresses are rejected.</p>{add.error && <p className="text-sm text-rose-200 md:col-span-2">{add.error.message}</p>}<button className="btn-primary justify-self-start" disabled={add.isPending}>{add.isPending ? 'Validating…' : 'Add backend'}</button></form>;
};

const BackendTestControl = ({ backendId, projectId }) => {
  const { api } = useAuth(); const client = useQueryClient(); const { state, start, cancel } = useBackendHealthTest(backendId);
  const testing = ['RUNNING', 'CANCELLING'].includes(state.status);
  const detail = state.status === 'COMPLETED' ? 'Health test completed.' : state.status === 'CANCELLED' ? 'Health test cancelled.' : state.status === 'FAILED' ? state.error?.message ?? 'Health test failed.' : null;
  return <div className="flex flex-col items-end gap-2">{testing ? <button className="btn-secondary" onClick={cancel} disabled={state.status === 'CANCELLING'}>{state.status === 'CANCELLING' ? 'Cancelling…' : 'Cancel test'}</button> : <button className="btn-secondary" onClick={() => start(api, () => client.invalidateQueries({ queryKey: ['backends', projectId] }))}>Test health</button>}{testing && <p className="text-xs text-relay-200">Testing backend health…</p>}{detail && <p className={`max-w-48 text-right text-xs ${state.status === 'FAILED' ? 'text-rose-200' : 'text-slate-400'}`}>{detail}</p>}</div>;
};

const Backends = ({ projectId, backends }) => <section className="space-y-5"><div><h2 className="text-xl font-semibold">Backends</h2><p className="mt-1 text-sm text-slate-400">Only registered public origins may receive gateway traffic.</p></div><BackendForm projectId={projectId} />{backends.length ? <div className="space-y-3">{backends.map((backend) => <article className="panel flex flex-col gap-4 p-4 sm:flex-row sm:items-center sm:justify-between" key={backend.id}><div><div className="flex items-center gap-2"><h3 className="font-semibold">{backend.name}</h3><span className="rounded bg-white/10 px-2 py-0.5 text-xs text-slate-300">{backend.role}</span></div><p className="mt-1 text-sm text-slate-400">{backend.originUrl}</p></div><div className="flex items-center gap-3"><StatusPill status={backend.health?.status ?? 'UNKNOWN'} /><BackendTestControl backendId={backend.id} projectId={projectId} /></div></article>)}</div> : <EmptyState title="Register your primary backend">Its health endpoint will be checked only after you explicitly enable monitoring.</EmptyState>}</section>;

const Help = ({ children }) => <details className="group relative inline-block align-middle"><summary className="ml-1 inline-flex h-4 w-4 cursor-pointer list-none items-center justify-center rounded-full border border-relay-300/60 text-[10px] text-relay-200 hover:bg-relay-300/15" aria-label="Show help">?</summary><div className="absolute z-10 mt-2 w-64 rounded-lg border border-relay-300/30 bg-[#0b1e39] p-3 text-xs font-normal leading-5 text-slate-200 shadow-xl">{children}</div></details>;
const NumberField = ({ label, help, value, onChange, min, max, detail }) => <label><span className="label">{label} <Help>{help}</Help></span><input className="field" type="number" min={min} max={max} defaultValue={value} onBlur={(event) => { const next = Number(event.target.value); if (Number.isInteger(next) && next !== value) onChange(next); }} /><span className="mt-1 block text-xs text-slate-500">{detail}</span></label>;

const BackendMonitor = ({ backend }) => {
  const { api } = useAuth(); const client = useQueryClient(); const query = useQuery({ queryKey: ['monitor', backend.id], queryFn: () => api.get(`/api/backends/${backend.id}/monitor`) }); const update = useMutation({ mutationFn: (body) => api.patch(`/api/backends/${backend.id}/monitor`, body), onSuccess: () => client.invalidateQueries({ queryKey: ['monitor', backend.id] }) });
  if (query.isLoading) return <article className="panel animate-pulse p-4"><div className="h-4 w-40 rounded bg-white/10" /></article>;
  if (query.error) return <ErrorState error={query.error} />;
  const { monitor, health } = query.data.data; const attempts = monitor.maxAttempts ?? 5; const retryDelay = monitor.retryDelaySeconds ?? 120;
  return <article className="panel overflow-hidden"><div className="border-b border-white/10 bg-slate-950/20 p-5"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><div className="flex items-center gap-2"><h3 className="font-semibold">{backend.name}</h3><StatusPill status={health.status} /></div><p className="mt-2 text-sm text-slate-400">{monitor.enabled ? `Checks every ${minutes(monitor.intervalSeconds)} minutes with a ${monitor.timeoutSeconds}s timeout` : 'Monitoring is disabled'}</p></div><button className={monitor.enabled ? 'btn-secondary' : 'btn-primary'} onClick={() => update.mutate({ enabled: !monitor.enabled })} disabled={update.isPending}>{update.isPending ? 'Saving…' : monitor.enabled ? 'Pause monitor' : 'Enable monitor'}</button></div></div><div className="p-5"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><NumberField label="Interval" value={monitor.intervalSeconds / 60} min="1" max="1440" detail="minutes" help="How often Relay starts a check cycle. Default: 10 minutes." onChange={(value) => update.mutate({ intervalSeconds: value * 60 })} /><NumberField label="Probe attempts" value={attempts} min="1" max="5" detail="per scheduled check" help="Retries after a failed probe before the check cycle is unsuccessful. Default: 5." onChange={(value) => update.mutate({ maxAttempts: value })} /><NumberField label="Retry delay" value={retryDelay / 60} min="1" max="60" detail="minutes" help="Wait between retry probes. Default: 2 minutes." onChange={(value) => update.mutate({ retryDelaySeconds: value * 60 })} /><NumberField label="Failure threshold" value={monitor.failureThreshold} min="1" max="20" detail="failed cycles" help="Fully failed cycles needed to create an incident. Default: 1." onChange={(value) => update.mutate({ failureThreshold: value })} /><NumberField label="Recovery threshold" value={monitor.recoveryThreshold} min="1" max="20" detail="successful cycles" help="Successful cycles needed before recovery. Default: 2." onChange={(value) => update.mutate({ recoveryThreshold: value })} /></div>{update.error && <p className="mt-4 text-sm text-rose-200">{update.error.message}</p>}</div></article>;
};

const Monitoring = ({ backends }) => <section className="space-y-5"><div className="monitoring-intro"><div><p className="label text-relay-300">Signal policy</p><h2 className="mt-2 text-xl font-semibold">Health monitoring</h2><p className="mt-1 max-w-2xl text-sm leading-6 text-slate-300">Relay confirms an outage only after every probe attempt is exhausted. The defaults use a 10-minute interval, five confirmation probes, and two healthy cycles before recovery.</p></div></div>{backends.length ? backends.map((backend) => <BackendMonitor key={backend.id} backend={backend} />) : <EmptyState title="Add a backend before enabling monitoring" />}</section>;

const Gateway = ({ projectId, backends }) => {
  const { api } = useAuth(); const client = useQueryClient(); const [slug, setSlug] = useState(''); const query = useQuery({ queryKey: ['gateway', projectId], queryFn: () => api.get(`/api/projects/${projectId}/gateway`) }); const update = useMutation({ mutationFn: (body) => api.patch(`/api/projects/${projectId}/gateway`, body), onSuccess: () => client.invalidateQueries({ queryKey: ['gateway', projectId] }) }); const config = query.data?.data;
  useEffect(() => { setSlug(config?.slug ?? ''); }, [config?.slug]);
  if (query.isLoading) return <Loading />; if (query.error) return <ErrorState error={query.error} />;
  const name = slug.trim().toLowerCase(); const valid = /^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(name) && name.length >= 3 && name.length <= 48; const hasBackends = backends.length > 0; const currentUrl = config.url ? `${GATEWAY_BASE_URL}${config.url}` : '';
  return <section className="space-y-5"><div><h2 className="text-xl font-semibold">Gateway</h2><p className="mt-1 text-sm text-slate-400">Relay routes only to backend origins registered in this project. It never accepts arbitrary proxy URLs.</p></div>{!hasBackends && <div className="rounded-xl border border-amber-300/30 bg-amber-300/10 p-4 text-sm text-amber-100">Register at least one backend before enabling a gateway. A gateway without a destination cannot receive traffic.</div>}<article className="panel space-y-5 p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="label">Gateway state</p><div className="mt-2"><StatusPill status={config.enabled ? 'HEALTHY' : 'OFFLINE'} /></div></div><button className={config.enabled ? 'btn-secondary' : 'btn-primary'} onClick={() => update.mutate(config.enabled ? { enabled: false } : { enabled: true, slug: name })} disabled={update.isPending || (!config.enabled && (!hasBackends || !valid))}>{update.isPending ? 'Saving…' : config.enabled ? 'Disable gateway' : 'Enable gateway'}</button></div><div className="border-t border-white/10 pt-5"><label className="block"><span className="label">Gateway name</span><div className="mt-2 flex overflow-hidden rounded-lg border border-white/10 bg-slate-950/30"><span className="flex items-center border-r border-white/10 px-3 text-sm text-slate-500">/g/</span><input className="min-w-0 flex-1 bg-transparent px-3 py-2.5 text-sm text-white outline-none" value={slug} onChange={(event) => setSlug(event.target.value.toLowerCase())} placeholder="payments-api" minLength="3" maxLength="48" autoCapitalize="none" disabled={config.enabled || update.isPending} /></div></label><div className="mt-2 flex flex-wrap items-center gap-3"><p className="text-xs text-slate-500">3–48 lowercase letters, numbers, and hyphens. This name must be unique across Relay.</p>{!config.enabled && <button className="btn-secondary" onClick={() => update.mutate({ slug: name })} disabled={update.isPending || !valid || name === (config.slug ?? '')}>Save gateway name</button>}</div>{!config.enabled && slug && !valid && <p className="mt-3 text-sm text-rose-200">Use 3–48 lowercase letters, numbers, or hyphens.</p>}{update.error && <p className="mt-3 text-sm text-rose-200">{update.error.message}</p>}</div><div className="border-t border-white/10 pt-5"><p className="label">Public gateway URL</p>{currentUrl ? <code className="mt-2 block overflow-auto rounded-lg bg-black/25 p-3 text-sm text-relay-300">{currentUrl}</code> : <p className="mt-2 text-sm text-slate-400">Choose a name, register a backend, and enable the gateway to create its public URL.</p>}</div></article></section>;
};

const Failover = ({ projectId, backends }) => { const { api } = useAuth(); const client = useQueryClient(); const query = useQuery({ queryKey: ['failover', projectId], queryFn: () => api.get(`/api/projects/${projectId}/failover`) }); const update = useMutation({ mutationFn: (body) => api.patch(`/api/projects/${projectId}/failover`, body), onSuccess: () => client.invalidateQueries({ queryKey: ['failover', projectId] }) }); const [choice, setChoice] = useState({ primaryBackendId: '', secondaryBackendId: '' }); if (query.isLoading) return <Loading />; if (query.error) return <ErrorState error={query.error} />; const { config, state, warning } = query.data.data; const selected = { primaryBackendId: choice.primaryBackendId || config.primaryBackendId || '', secondaryBackendId: choice.secondaryBackendId || config.secondaryBackendId || '' }; return <section className="space-y-5"><div><h2 className="text-xl font-semibold">Health-based failover</h2><p className="mt-1 text-sm text-slate-400">Only a healthy secondary is selected after the primary reaches its monitoring failure threshold.</p></div><div className="rounded-xl border border-amber-300/30 bg-amber-300/10 p-4 text-sm text-amber-100">{warning}</div><article className="panel p-5"><div className="flex items-center justify-between"><div><p className="label">Current routing state</p><div className="mt-2"><StatusPill status={state.mode} /></div></div><button className={config.enabled ? 'btn-secondary' : 'btn-primary'} disabled={backends.length < 2} onClick={() => update.mutate({ enabled: !config.enabled, ...selected })}>{config.enabled ? 'Disable failover' : 'Enable failover'}</button></div><div className="mt-5 grid gap-3 border-t border-white/10 pt-5 sm:grid-cols-2"><label><span className="label">Primary backend</span><select className="field" value={selected.primaryBackendId} onChange={(event) => setChoice({ ...choice, primaryBackendId: event.target.value })}><option value="">Choose primary</option>{backends.map((backend) => <option key={backend.id} value={backend.id}>{backend.name}</option>)}</select></label><label><span className="label">Secondary backend</span><select className="field" value={selected.secondaryBackendId} onChange={(event) => setChoice({ ...choice, secondaryBackendId: event.target.value })}><option value="">Choose secondary</option>{backends.map((backend) => <option key={backend.id} value={backend.id}>{backend.name}</option>)}</select></label></div></article></section>; };
const Events = ({ projectId, kind }) => { const { api } = useAuth(); const endpoint = kind === 'alerts' ? 'alerts' : 'logs'; const query = useQuery({ queryKey: [endpoint, projectId], queryFn: () => api.get(`/api/projects/${projectId}/${endpoint}`) }); if (query.isLoading) return <Loading />; if (query.error) return <ErrorState error={query.error} />; const events = query.data.data; return <section><h2 className="text-xl font-semibold">{kind === 'alerts' ? 'Alerts' : 'Operational logs'}</h2>{events.length ? <div className="mt-5 space-y-3">{events.map((event) => <article className="panel flex gap-4 p-4" key={event.id}><StatusPill status={event.severity === 'critical' ? 'UNHEALTHY' : 'UNKNOWN'} /><div><p className="font-medium">{event.type.replaceAll('_', ' ')}</p><p className="mt-1 text-sm text-slate-400">{event.message}</p><p className="mt-2 text-xs text-slate-500">{new Date(event.timestamp).toLocaleString()}</p></div></article>)}</div> : <div className="mt-5"><EmptyState title={`No ${kind} yet`} /></div>}</section>; };
const ProjectSettings = ({ project }) => { const { api } = useAuth(); const client = useQueryClient(); const [name, setName] = useState(project.name); const [description, setDescription] = useState(project.description ?? ''); const update = useMutation({ mutationFn: () => api.patch(`/api/projects/${project.id}`, { name, description }), onSuccess: () => { client.invalidateQueries({ queryKey: ['project', project.id] }); client.invalidateQueries({ queryKey: ['projects'] }); } }); return <section><h2 className="text-xl font-semibold">Project settings</h2><form className="panel mt-5 max-w-xl space-y-4 p-5" onSubmit={(event) => { event.preventDefault(); update.mutate(); }}><label className="block"><span className="label">Name</span><input className="field" value={name} minLength="2" onChange={(event) => setName(event.target.value)} /></label><label className="block"><span className="label">Description</span><textarea className="field" rows="3" value={description} onChange={(event) => setDescription(event.target.value)} /></label>{update.error && <p className="text-sm text-rose-200">{update.error.message}</p>}<button className="btn-primary" disabled={update.isPending}>Save changes</button></form></section>; };
const Overview = ({ project, backends, onBackends }) => <section className="grid gap-5 lg:grid-cols-[1.25fr_0.75fr]"><article className="panel p-5"><h2 className="text-xl font-semibold">Onboarding</h2><ol className="mt-5 space-y-4">{[['1', 'Register a backend', 'Add a public origin and health path.'], ['2', 'Enable monitoring', 'Use the guided minutes-based policy.'], ['3', 'Enable gateway', 'Put Relay in front of the registered origin.'], ['4', 'Optionally enable failover', 'Only with compatible shared state.']].map(([number, title, copy]) => <li className="flex gap-3" key={title}><span className="grid h-7 w-7 place-items-center rounded-full bg-white/10 text-sm">{number}</span><div><p className="font-medium">{title}</p><p className="text-sm text-slate-400">{copy}</p></div></li>)}</ol>{!backends.length && <button className="btn-primary mt-6" onClick={onBackends}>Add first backend</button>}</article><article className="panel p-5"><h2 className="font-semibold">Current scope</h2><div className="mt-4 space-y-3 text-sm"><div className="flex justify-between"><span className="text-slate-400">Backends</span><span>{backends.length}</span></div><div className="flex justify-between"><span className="text-slate-400">Gateway policy</span><span>Registered only</span></div><div className="flex justify-between"><span className="text-slate-400">Project version</span><span>v{project.version}</span></div></div></article></section>;

export const ProjectWorkspace = () => {
  const { projectId } = useParams(); const location = useLocation(); const navigate = useNavigate(); const basePath = `/projects/${projectId}`; const { project, backends } = useProjectData(projectId);
  if (project.isLoading || backends.isLoading) return <Loading />; if (project.error) return <ErrorState error={project.error} />; if (backends.error) return <ErrorState error={backends.error} />;
  const selected = sections.find((section) => location.pathname === (section.key ? `${basePath}/${section.key}` : basePath))?.key ?? ''; const projectData = project.data.data; const backendData = backends.data.data;
  const content = { '': <Overview project={projectData} backends={backendData} onBackends={() => navigate(`${basePath}/backends`)} />, backends: <Backends projectId={projectId} backends={backendData} />, monitoring: <Monitoring backends={backendData} />, gateway: <Gateway projectId={projectId} backends={backendData} />, failover: <Failover projectId={projectId} backends={backendData} />, alerts: <Events projectId={projectId} kind="alerts" />, logs: <Events projectId={projectId} kind="logs" />, settings: <ProjectSettings project={projectData} /> }[selected];
  return <div className="space-y-6"><div><Link className="text-sm font-medium text-relay-400 hover:text-relay-300" to="/projects">← Projects</Link><div className="mt-3 flex flex-wrap items-center justify-between gap-3"><div><p className="label text-relay-400">Project</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">{projectData.name}</h1></div><StatusPill status="UNKNOWN" /></div></div><nav className="flex gap-1 overflow-auto border-b border-white/10 pb-px">{sections.map((section) => <NavLink key={section.key} end to={section.key ? `${basePath}/${section.key}` : basePath} className={({ isActive }) => `whitespace-nowrap border-b-2 px-3 py-3 text-sm font-medium transition ${isActive ? 'border-relay-400 text-relay-300' : 'border-transparent text-slate-400 hover:text-white'}`}>{section.label}</NavLink>)}</nav>{content}</div>;
};
